### PR TITLE
Update to Serde 1.0

### LINKED ISSUE #25: Update to Serde 1.0
Serde 0.9 release notes: https://github.com/serde-rs/serde/releases/tag/v0.9.0
Serde 1.0 release notes: https://github.com/serde-rs/serde/releases/tag/v1.0.0

### LINKED ISSUE #26: Drop rustc-serialize dependency
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

### PR DESCRIPTION
**Pull request by dtolnay**
Supersedes #23. Fixes #25 and fixes #26.

### CODE REVIEW

**Comment by demurgos** [comment]
@reem Could you take a look at this MR ? I am using https://github.com/dtolnay/ordered-float/tree/serde-1.0 it works fine.

**Comment by demurgos** [comment]
@reem 
I've been using using dtolnay:serde-1.0 for two weeks now, without any issue. Could you merge this PR?

**Comment by reem** [comment]
Looks great, sorry for the slow turnaround!

**Comment by dtolnay** [comment]
Thanks, could we get a release as well when you're ready?

**Pull request merged**
