### PR TITLE
Split `rkyv` feature by `size_xx`.

### PR DESCRIPTION
**Pull request by n3vu0r**
This will support `rkyv` with different size types.

### CODE REVIEW

**Comment by mbrubeck** [comment]
Hmm, is there a way we can do this without a breaking change for users of the existing `rkyv` feature?

**Comment by n3vu0r** [comment]
This should be non-breaking now. I hope I've fixed the workflow. I'm avoiding namespaced-features like `dep:rkyv` which is not supported by the MSRV of `1.36.0`.

**Comment by mbrubeck** [comment]
Thanks!  By the way, I'm planning to bump the MSRV to 1.60 soon for #119 which also uses namespaced features, so we could use them here too...

**Comment by n3vu0r** [comment]
Great, that makes it a bit nicer.

**Comment by mbrubeck** [comment]
This is now published in ordered-float 3.7.0.

**Comment by n3vu0r** [comment]
Thanks for the update.

**Pull request merged**
