### PR TITLE
Update unreachable and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Ping ? :)

**Comment by Eijebong** [comment]
Reping :D

**Comment by Eijebong** [comment]
Bump ?

**Comment by mbrubeck** [comment]
I published a (hopefully temporary) fork that includes this change: https://crates.io/crates/new-ordered-float

**Comment by mbrubeck** [comment]
Merged in #47.

**Pull request closed without merging**
