### PR TITLE
impl Bounded for OrderedFloat, NotNaN

### PR DESCRIPTION
**Pull request by andersk**

### CODE REVIEW

**Comment by mbrubeck** [comment]
I published a (hopefully temporary) fork that includes this change: https://crates.io/crates/new-ordered-float

**Comment by reem** [comment]
@mbrubeck I've added you as a cargo owner and a collaborator to this repo, feel free to update as you see fit.

**Comment by mbrubeck** [comment]
Thanks!

**Comment by mbrubeck** [comment]
Merged in #47.

**Comment by mbrubeck** [comment]
@reem I'm not yet listed as an owner on crates.io and don't see any [pending invitations](https://crates.io/me/pending-invites).  Perhaps there was a problem with crates.io's invitation process... Could you try `cargo owner --add mbrubeck` again?

**Comment by andersk** [comment]
This wasn’t merged; there’s still no `Bounded` impl for `OrderedFloat`.

**Pull request merged**
