### PR TITLE
Derive traits for `rand` types

### LINKED ISSUE #116: `rand` types missing traits
In particular, `UniformNotNan` and `UniformOrdered` lack traits. Ideally, they should implement the same traits as `UniformFloat`. At the very least, they should implement `Debug` and `Clone`. Additionally, they should implement Serde traits if `serde` is enabled.

### PR DESCRIPTION
**Pull request by JustinLovinger**
Closes #116.

### CODE REVIEW

**Comment by JustinLovinger** [comment]
What is the story for Rust 1.36.0 and this package? Is the intent to continue supporting 1.36.0 going forward? If so, I can work around the `Features and dependencies cannot have the same name` issue by renaming the `serde` feature I defined to something like `serde1`, but that is a worse experience for users on stable Rust.

**Comment by mbrubeck** [comment]
This would require Rust 1.60 or newer, correct?  I'm generally willing to drop support for older versions, but this would be a pretty big jump.  On the other hand, Rust 1.60 will be a full year old within a few months, so maybe that would be a reasonable time to do this.  Let me think about it.

If you'd like to separate the non-Serde traits into their own PR, I could definitely merge and release that right away.

**Comment by JustinLovinger** [comment]
> This would require Rust 1.60 or newer, correct?

I believe so.

> If you'd like to separate the non-Serde traits into their own PR, I could definitely merge and release that right away.

I can wait while you deliberate, and I do not think anyone else urgently needs this.

**Comment by mbrubeck** [comment]
Okay, my current plan is to merge this in a few months, on the theory that the number of people who are still on Rust 1.59 and earlier will have decreased further by then.

**Comment by mbrubeck** [comment]
This is now published in ordered-float 3.7.0.

**Pull request merged**
